title: Stories told and untold
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2382424715906382
  brandStrength: 0.4630017746239901
  rhythmicContrast: 0.6240060832351446
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.866567509714514
typography_spectrum: 0.08282515686005354
description: 'Story, EDC, Kids'
navigation:
  - name: About me
    id: 4aec0147-693f-4ec4-ba47-abb9f280f2a7
    type: content
  - name: Impressum
    id: a50c18c2-0d0e-41c7-80fc-4b8806ebb62b
    type: content
layout_spectrum: 1
name: On a way through life
